export const ADMIN_TEXT = {
  layout: {
    logo: 'Admin',
    searchPlaceholder: 'Tìm nhanh đơn hàng, sản phẩm...',
    notifications: 'Thông báo',
    settings: 'Cài đặt',
    adminName: 'Admin',
    sidebar: {
      description: 'Thiết lập gateway thanh toán, phí ship, email thông báo.',
      cta: 'Cấu hình ngay',
    },
    nav: {
      dashboard: 'Tổng quan',
      orders: 'Đơn hàng',
      products: 'Sản phẩm',
      categories: 'Danh mục',
      customers: 'Khách hàng',
      promotions: 'Khuyến mãi',
      content: 'Nội dung',
      settings: 'Cấu hình',
    },
    breadcrumbs: {
      orderDetail: 'Chi tiết',
      orderList: 'Danh sách',
      productList: 'Danh sách',
      categoryList: 'Danh sách',
      customerList: 'Danh sách',
      promoList: 'Danh sách',
    },
  },
  dashboard: {
    title: 'Tổng quan',
    searchPlaceholder: 'Tìm đơn hàng, khách hàng...',
    stats: {
      ordersToday: 'Đơn hôm nay',
      revenue: 'Doanh thu',
      pending: 'Chờ xử lý',
      newCustomers: 'Khách mới',
    },
    quickViews: {
      urgentOrders: 'Đơn xử lý gấp',
      pendingOrders: 'Đơn chờ xác nhận',
      lowStockProducts: 'Sản phẩm cảnh báo kho',
      expiringPromos: 'Khuyến mãi sắp hết hạn',
    },
    revenue: {
      title: 'Doanh thu 7 ngày',
      comparison: '+8% vs tuần trước',
      axes: { day: 'Ngày', vnd: 'VNĐ' },
    },
    actionCenter: {
      title: 'Action Center',
      addProduct: 'Thêm sản phẩm',
      createVoucher: 'Tạo voucher',
      processReturn: 'Xử lý đổi/trả',
      quickProcess: 'Xử lý nhanh',
    },
    actionFeed: {
      title: 'Action Feed',
      openList: 'Mở danh sách',
      viewProducts: 'Xem sản phẩm',
      viewPromo: 'Vào khuyến mãi',
    },
    recentOrders: {
      title: 'Đơn hàng gần đây',
      viewAll: 'Xem tất cả',
      columns: {
        order: 'Đơn hàng',
        priority: 'Ưu tiên',
        waitTime: 'Thời gian chờ',
        total: 'Tổng tiền',
        actions: 'Hành động',
      },
      priority: {
        high: 'Cao',
        medium: 'Vừa',
        low: 'Thấp',
      },
      confirm: 'Xác nhận',
      empty: {
        title: 'Chưa có đơn gần đây',
        description: 'Đơn mới sẽ hiển thị tại đây để team xử lý nhanh.',
      },
    },
    topProducts: {
      title: 'Top bán chạy',
      sales: 'bán',
      stockLeft: 'Tồn kho còn',
      empty: {
        title: 'Chưa có dữ liệu top bán chạy',
        description: 'Sản phẩm bán chạy sẽ xuất hiện sau khi có đủ dữ liệu bán hàng.',
      },
    },
    buttons: {
      viewOrders: 'Xem đơn',
      addProduct: 'Thêm sản phẩm',
    },
  },
  common: {
    status: {
      running: 'Đang chạy',
      paused: 'Tạm dừng',
      expired: 'Hết hạn',
      done: 'Hoàn tất',
      shipping: 'Đang giao',
      pending: 'Chờ xác nhận',
      canceled: 'Đã hủy',
      active: 'Đang bán',
      low: 'Sắp hết',
      out: 'Hết hàng',
    },
    filter: 'Bộ lọc',
    statusLabel: 'Trạng thái',
    keyword: 'Từ khóa',
    clearFilters: 'Xóa bộ lọc',
    previous: 'Trước',
    next: 'Tiếp',
    selected: (count: number, noun: string) => `${count} ${noun} đã chọn`,
    showing: (start: number, end: number, total: number, noun: string) => `Hiển thị ${start}-${end} của ${total} ${noun}`,
    aria: {
      selectAll: 'Chọn tất cả',
      selectItem: (code: string) => `Chọn ${code}`,
    },
  },
  orders: {
    title: 'Đơn hàng',
    searchPlaceholder: 'Tìm mã đơn, tên khách hoặc SĐT...',
    panelTitle: 'Danh sách đơn hàng',
    overview: 'Tổng quan',
    tableAria: 'Danh sách đơn hàng',
    tabs: {
      all: 'Tất cả',
      urgent: 'Xử lý gấp',
      pending: 'Chờ xác nhận',
      packing: 'Đang đóng gói',
      shipping: 'Đang giao',
      done: 'Hoàn tất',
      canceled: 'Đã hủy',
    },
    empty: {
      searchTitle: 'Không tìm thấy đơn hàng phù hợp',
      searchDescription: 'Thử đổi từ khóa tìm kiếm hoặc xóa bộ lọc trạng thái.',
      defaultTitle: 'Chưa có đơn hàng nào',
      defaultDescription: 'Đơn mới sẽ xuất hiện tại đây khi khách hàng đặt hàng.',
    },
    columns: {
      orderCode: 'Mã đơn',
      customer: 'Khách hàng',
      total: 'Tổng tiền',
      payment: 'Thanh toán',
      shipping: 'Vận chuyển',
      createdAt: 'Ngày đặt',
      actions: 'Hành động',
    },
    selectedNoun: 'đơn hàng',
    bulkActions: {
      confirm: 'Xác nhận',
      printInvoice: 'In hóa đơn',
      modalTitle: 'Xác nhận đơn hàng hàng loạt',
      modalDescription: (count: number) => `Bạn đang thao tác trên ${count} đơn hàng đã chọn.`,
      eligibleLabel: 'Đơn hợp lệ chuyển sang Đang đóng gói',
      skippedLabel: 'Đơn bị bỏ qua do sai trạng thái',
      cancel: 'Hủy',
      confirmBulk: 'Xác nhận hàng loạt',
    },
  },
  products: {
    title: 'Sản phẩm',
    searchPlaceholder: 'Tìm tên, SKU...',
    addProduct: 'Thêm sản phẩm',
    tableAria: 'Danh sách sản phẩm',
    tabs: {
      all: 'Tất cả',
      stockAlert: 'Cảnh báo kho',
      active: 'Đang bán',
      low: 'Sắp hết',
      out: 'Hết hàng',
    },
    empty: {
      searchTitle: 'Không tìm thấy sản phẩm phù hợp',
      searchDescription: 'Thử đổi từ khóa hoặc chuyển tab trạng thái khác.',
      defaultTitle: 'Chưa có sản phẩm trong danh sách',
      defaultDescription: 'Thêm sản phẩm mới để bắt đầu quản lý kho và biến thể.',
    },
    columns: {
      product: 'Sản phẩm',
      category: 'Danh mục',
      price: 'Giá',
      stock: 'Tồn kho',
      status: 'Trạng thái',
      actions: 'Hành động',
    },
    selectedNoun: 'sản phẩm',
    floatingActions: {
      changeStatus: 'Đổi trạng thái',
      exportExcel: 'Xuất Excel',
      delete: 'Xóa',
    },
  },
  categories: {
    title: 'Danh mục',
    searchPlaceholder: 'Tìm danh mục...',
    addCategory: 'Thêm danh mục',
    tableAria: 'Danh sách danh mục',
    tabs: {
      all: 'Tất cả',
      visible: 'Đang hiện',
      hidden: 'Ẩn',
      menu: 'Có trên menu',
    },
    empty: {
      searchTitle: 'Không tìm thấy danh mục phù hợp',
      searchDescription: 'Hãy thử từ khóa khác hoặc đổi tab lọc.',
      defaultTitle: 'Chưa có danh mục nào',
      defaultDescription: 'Tạo danh mục đầu tiên để bắt đầu phân loại sản phẩm.',
    },
    columns: {
      image: 'Hình ảnh',
      name: 'Tên danh mục',
      parent: 'Danh mục cha',
      productCount: 'Số lượng SP',
      order: 'Thứ tự',
      status: 'Trạng thái',
      actions: 'Hành động',
    },
    selectedNoun: 'danh mục',
    floatingActions: {
      deleteSelected: 'Xóa đã chọn',
      changeStatus: 'Đổi trạng thái',
      undo: 'Hoàn tác',
    },
    aria: {
      selectAll: 'Chọn tất cả',
      selectItem: (code: string) => `Chọn ${code}`,
    },
  },
  customers: {
    title: 'Khách hàng',
    searchPlaceholder: 'Tìm tên, email, số điện thoại...',
    resultLabel: (count: number) => `Kết quả: ${count}`,
    tableAria: 'Danh sách khách hàng',
    tabs: {
      all: 'Tất cả',
      new: 'Khách mới',
      vip: 'Khách VIP',
      banned: 'Bị khóa',
    },
    summary: {
      group: 'Nhóm',
      tier: 'Hạng',
      spend: 'Chi tiêu',
    },
    empty: {
      searchTitle: 'Không tìm thấy khách hàng phù hợp',
      searchDescription: 'Hãy thử thay đổi bộ lọc hạng, chi tiêu hoặc từ khóa tìm kiếm.',
      defaultTitle: 'Chưa có khách hàng nào',
      defaultDescription: 'Khách hàng mới sẽ được ghi nhận tự động sau khi phát sinh đơn hàng.',
    },
    columns: {
      customer: 'Khách hàng',
      phone: 'Số điện thoại',
      tier: 'Hạng thành viên',
      totalOrders: 'Tổng đơn',
      totalSpent: 'Tổng chi tiêu',
      status: 'Trạng thái',
      lastOrder: 'Đơn gần nhất',
      actions: 'Hành động',
    },
    selectedNoun: 'khách hàng',
    floatingActions: {
      sendVoucher: 'Gửi Voucher',
      lockAccount: 'Khóa tài khoản',
      sendEmail: 'Gửi Email',
    },
    drawer: {
      title: 'Chi tiết khách hàng',
      tabs: {
        activity: 'Hoạt động',
        preferences: 'Sở thích',
        notes: 'Ghi chú Admin',
      },
      notePlaceholder: 'Ví dụ: Khách hay đổi trả size, ưu tiên liên hệ buổi tối...',
      close: 'Đóng',
      saveNote: 'Lưu ghi chú',
      lockTitle: 'Khóa tài khoản',
      lockTitleBulk: 'Khóa nhiều tài khoản',
      status: {
        active: 'Đang hoạt động',
        banned: 'Bị khóa',
      },
    },
    filters: {
      tierAll: 'Tất cả hạng',
      spendAll: 'Tất cả chi tiêu',
      spendUnder1m: 'Dưới 1 triệu',
      spend1m5m: '1 - 5 triệu',
      spend5m10m: '5 - 10 triệu',
      spend10mPlus: 'Trên 10 triệu',
    },
  },
  promotions: {
    title: 'Khuyến mãi',
    searchPlaceholder: 'Tìm theo tên chiến dịch, mã voucher...',
    promoType: 'Loại khuyến mãi',
    create: 'Tạo mã mới',
    panelTitle: 'Danh sách voucher',
    tableAria: 'Danh sách voucher khuyến mãi',
    tabs: {
      all: 'Tất cả',
      running: 'Đang chạy',
      paused: 'Tạm dừng',
      expired: 'Hết hạn',
    },
    empty: {
      searchTitle: 'Không tìm thấy chiến dịch phù hợp',
      searchDescription: 'Hãy thử thay đổi từ khóa hoặc tab trạng thái.',
      defaultTitle: 'Chưa có chiến dịch khuyến mãi nào',
      defaultDescription: 'Tạo voucher đầu tiên để bắt đầu vận hành chiến dịch sale.',
    },
    columns: {
      voucherName: 'Tên voucher',
      discountType: 'Loại giảm giá',
      value: 'Giá trị',
      condition: 'Điều kiện',
      quantity: 'Số lượng',
      schedule: 'Thời gian',
      status: 'Trạng thái',
      actions: 'Hành động',
    },
    selectedNoun: 'chiến dịch',
    floatingActions: {
      pauseSelected: 'Tạm dừng đã chọn',
      deleteSelected: 'Xóa đã chọn',
    },
    drawer: {
      eyebrow: 'Marketing Campaign',
      editTitle: 'Chỉnh sửa mã khuyến mãi',
      createTitle: 'Tạo mã khuyến mãi mới',
      section1: 'Section 1: Thông tin chung',
      section2: 'Section 2: Cấu hình giảm giá',
      section3: 'Section 3: Điều kiện & Giới hạn',
      section4: 'Section 4: Lịch trình',
      cancel: 'Hủy',
      save: 'Lưu thay đổi',
      create: 'Tạo voucher',
      placeholders: {
        name: 'Ví dụ: Summer Flash Sale',
        code: 'VD: SUMMER20',
        description: 'Mô tả ngắn gọn mục tiêu và đối tượng áp dụng...',
      },
    },
  },
  orderDetail: {
    back: 'Quay lại',
    orderPrefix: 'Đơn hàng',
    actions: {
      printInvoice: 'In hóa đơn',
      refund: 'Hoàn tiền',
      cancelOrder: 'Hủy đơn',
      exportAudit: 'Xuất audit log',
      confirmUpdate: 'Xác nhận cập nhật',
      cancel: 'Hủy',
    },
    sections: {
      orderItems: 'Sản phẩm trong đơn',
      paymentInfo: 'Thông tin thanh toán',
      customerShipping: 'Khách hàng & vận chuyển',
      timeline: 'Lịch sử đơn hàng',
    },
  },
  workflow: {
    transitionReasons: {
      customerCancel: 'Khách hàng yêu cầu hủy',
      outOfStock: 'Hết hàng',
      paymentFailed: 'Thanh toán thất bại',
      duplicate: 'Trùng đơn',
      shippingDelay: 'Giao chậm trễ',
      customerRequest: 'Khách yêu cầu đổi',
      qualityIssue: 'Lỗi chất lượng',
      wrongItem: 'Giao sai sản phẩm',
      fraudSuspected: 'Nghi ngờ gian lận',
      systemError: 'Lỗi hệ thống',
    },
  },
} as const;
